### PR TITLE
Add search property to location if doesn't exist

### PR DESCRIPTION
**Pull request by aliciaggames**
Related to [this change](https://github.com/gluckgames/ingine/pull/1054/files#diff-41cfc59c4eb5d50f45bb67334b81f0f97a9c81ce0cad9b916e3914f998d756d9)
The property `window.location.search` is required when an instance of `feim` module is created in unit tests since they are using a mocked window. To avoid adding this line (`global.window.location.search = "";`) on each project we added the `search` property in `mock-browser` when `win` object is created.

### CODE REVIEW

**Comment by ibaiimaz** [comment]
LGTM, but I was part of this decision so will wait if someone else checks it

**Comment by grahamrhay** [comment]
have you opened a pr with the upstream?

**Comment by aliciaggames** [comment]
> have you opened a pr with the upstream?

you mean a PR in projects where mock-browser is being used?

**Comment by grahamrhay** [comment]
er, no. I mean a pr here: https://github.com/darrylwest/mock-browser

**Comment by aliciaggames** [comment]
> er, no. I mean a pr here: https://github.com/darrylwest/mock-browser

ok! I misunderstood you 😉 I'll do it

**Comment by grahamrhay** [comment]
we don't want to maintain a fork, if we don't have to

**Comment by aliciaggames** [comment]
I checked previous PRs in `gluckgames/mock-browser` and those changes are not in https://github.com/darrylwest/mock-browser 🤔
https://github.com/gluckgames/mock-browser/blob/master/lib/MockBrowser.js#L11
https://github.com/darrylwest/mock-browser/blob/master/lib/MockBrowser.js#L10

**Pull request merged**
